services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WebEtDesign\FaqBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Controller,Entity,Migrations,Tests,Kernel.php}'

  WebEtDesign\FaqBundle\Controller\:
    resource: '../../Controller/*'
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\FaqBundle\CMS\FaqPage:
    autowire: true
    autoconfigure: true

  WebEtDesign\FaqBundle\CMS\CategoryPage:
    autowire: true
    autoconfigure: true

